### ISSUE TITLE
Migrate from AppCfg to gcloud

### ISSUE THREAD

**Issue by dskecse** [stachern/bseu_schedule#10]
The app has been updated to use `gcloud` instead of the [deprecated standalone App Engine SDK which is now shut down](https://cloud.google.com/appengine/docs/standard/python/sdk-gcloud-migration).

The issue is that it's now required to [have Cloud Build API enabled](https://console.cloud.google.com/apis/library/cloudbuild.googleapis.com?project=bseu-api&flow=gcp) for a project which in turn requires a [billing](https://console.cloud.google.com/billing/linkedaccount?project=bseu-api) attached to a project to deploy it, but I was unable to do it because of the permissions error:

```
User missing permission 'resourcemanager.projects.createBillingAssignment' to link a billing account to project.
```

![Screenshot 2021-09-19 at 23 13 48](https://user-images.githubusercontent.com/1451690/133943401-a8685db6-3c6e-4b4a-8453-6489d38cec1c.png)

@stachern perhaps, the easiest thing to do here is for you to grant me the missing `resourcemanager.projects.createBillingAssignment` permission, so I could link my billing info?

**Comment by stachern** [comment]
Well, that's a flash from the past (first commit - 10 years ago :)). Do you know if any of this code is still functional/relevant? Should we just nuke the repo and the gcloud project associated?

**Comment by dskecse** [comment]
lol I couldn't agree more! but most of this code is still functional and being used. and I'd definitely nuke them if I had enough capacity to rewrite the app

**Comment by stachern** [comment]
I gave you 'owner' on the project, so I believe you should be able to do anything now. 

Man, I am surprised that this is still alive. Someone should really take over it and fix the gcal integration, that's the whole reason I made it back then.
