### ISSUE TITLE
Add parser for university teacher's calendar

### ISSUE THREAD

**Issue by stachern** [stachern/bseu_schedule#4]
Request to add export for university teachers: [original post](http://narxoz.org/forum/index.php/topic/22046-%D0%B1%D1%8B%D1%81%D1%82%D1%80%D1%8B%D0%B9-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82-%D1%80%D0%B0%D1%81%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81-%D1%81%D0%B0%D0%B9%D1%82%D0%B0-%D0%B1%D0%B3%D1%8D%D1%83-%D0%B2-%D0%B3%D1%83%D0%B3%D0%BB-%D0%BA%D0%B0/#entry134146)

**Comment by andc0** [comment]
Развивается ли еще проект? Было бы очень неплохо увидеть вариант этого сервиса в версии и для преподавателей.

**Comment by Rebound** [comment]
andc0, думаю, что нет. Автор ранее писал, что, к сожалению, у него уже нет времени на поддержку данного проекта. Предлагал передать "поддержку и развитие" любому энтузиасту.
